# **Feature Engineering**

## Objectives

* Split the data into train and test sets
* Build a reproducible preprocessing pipeline that implements the feature transformations validated in the [feature exploration](/jupyter_notebooks/06_feature_exploration.ipynb) notebook as well as required encoding
* Apply SmartCorrelatedFeatures to produce a definitive list of features on which to train the model
* Fit the pipeline to on train data and transform both train and test sets 


## Inputs

* outputs/datasets/cleaned/HotelBookingsClean.csv
* outputs/correlation/TopFeatures.csv

## Outputs

* Feature engineering pipeline saved as preprocessing_pipeline.pkl
* X_train, X_test, y_train and y_test to outputs/ml_pipeline/cancel_predict/v1 as .csv

## Additional Comments

* ⚠️ TBC ⚠️

---

# Change working directory

We need to change the working directory from its current folder to its parent folder
* We access the current directory with os.getcwd()

In [1]:
import os
current_dir = os.getcwd()
current_dir

'/home/niall/PP4/cancel-protect/jupyter_notebooks'

We want to make the parent of the current directory the new current directory
* os.path.dirname() gets the parent directory
* os.chdir() defines the new current directory

In [3]:
os.chdir(os.path.dirname(current_dir))

current_dir = os.getcwd()
current_dir

'/home/niall/PP4/cancel-protect'

# Load Data

In [4]:
import pandas as pd

df = pd.read_csv("outputs/datasets/cleaned/HotelBookingsClean.csv")
df.head(3)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,C,3,No Deposit,0,0,0,Transient,0.0,0,0
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,C,4,No Deposit,0,0,0,Transient,0.0,0,0
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,C,0,No Deposit,0,0,0,Transient,75.0,0,0

**Decisions from Feature Exploration**

| Feature | Decision |
| --- | --- |
| arrival_date_year | Drop |
| lead_time | Category bin |
| previous_cancellations | Binary flag |

In [5]:
top_features = pd.read_csv("outputs/correlation/TopFeatures.csv")
top_features.head(3)

,Unnamed: 0,Feature,Raw/Engineered,Pearson,Spearman,PPS,Above Threshold
0,1,lead_time,Raw,0.292693,0.316357,0.215872,Yes
1,12,country,Raw,NaN,NaN,0.307594,Yes
2,13,market_segment,Raw,NaN,NaN,0.208675,Yes

---

## Split train and test set

In [16]:
from sklearn.model_selection import train_test_split

df_data = df.drop("is_canceled", axis=1)
target = df["is_canceled"]

print(f"df_data shape: {df_data.shape}, target shape: {target.shape}")

X_train, X_test, y_train, y_test = train_test_split(
    df_data, target, test_size=0.2, random_state=4, stratify=target
)

display_shapes = pd.Series({"X_train": X_train.shape,
              "X_test": X_test.shape,
              "y_train": y_train.shape,
              "y_test": y_test.shape}, name="split_shapes")
display_shapes

df_data shape: (119187, 29), target shape: (119187,)

X_train    (95349, 29)
X_test     (23838, 29)
y_train       (95349,)
y_test        (23838,)
Name: split_shapes, dtype: object

---

NOTE

* You may add as many sections as you want, as long as it supports your project workflow.
* All notebook's cells should be run top-down (you can't create a dynamic wherein a given point you need to go back to a previous cell to execute some task, like go back to a previous cell and refresh a variable content)

---

# Push files to Repo

* In case you don't need to push files to Repo, you may replace this section with "Conclusions and Next Steps" and state your conclusions and next steps.

In [ ]:
import os
try:
  # create here your folder
  # os.makedirs(name='')
except Exception as e:
  print(e)